### ISSUE TITLE
Wrong exception catch when extracted tables don't exist

### ISSUE THREAD

**Issue by iross** [UW-COSMOS/Cosmos#177]
When the table extraction fails and returns `None` instead of a dataframe object, we used to trap it via an AttributeError:

https://github.com/UW-COSMOS/Cosmos/blob/master/cosmos/ingestion/ingest/utils/table_extraction.py#L274

Now that we're returning an array of dataframe objects, we hit a TypeError if df is None

**Comment by ryansun117** [comment]
I did some debugging following the changes, it seems both TypeError and AttributeError are possible. At line , there are two cases since df is a list of dataframes:

1. If `df == [None, None]`, meaning either Camelot or Pdfplumber successfully extracted a table, but one or both of the tables was None. Then, attempting to access None.to_csv() would throw `AttibuteError: 'NoneType' object has no attribute 'to_csv'`
2. If `df == None`, meaning both Camelot and Pdfplumber extraction failed. Then, attempting to access `df[0]` would throw `TypeError: 'NoneType' object is not subscriptable`

A solution would be to catch both TypeError and AttributeError. This ensures the process continues to run. Should we add more detailed logging statements for each type of exception?
