### ISSUE TITLE
stanford-corenlp-full-2018-10-05.zip link may not work

### ISSUE THREAD

**Issue by SeanXiaoyuSun** [UW-COSMOS/Cosmos#41]
When http://nlp.stanford.edu/software/stanford-corenlp-full-2018-10-05.zip is not working, running docker-compose up will get stuck at 
`step 39/51: RUN wget http://nlp.stanford.edu/software/stanford-corenlp-full-2018-10-05.zip`.

A way to solve this is manually download this .zip file from the link above. Then unzip it and paste it to the same directory as Dockerfile's. 

In Dockerfile, the downloading part also need to be commented out:
```
108 USER user
109
110 # RUN wget http://nlp.stanford.edu/software/stanford-corenlp-full-2018-10-05.zip
111 # RUN unzip stanford-corenlp-full-2018-10-05.zip
112 # RUN rm stanford-corenlp-full-2018-10-05.zip
```

**Comment by ankur-gos** [comment]
@iross is this a docker configuration issue?

**Comment by iross** [comment]
Either:
1. The docker setup isn't set up correctly on the host and the resulting
image can't connect out during the build process
or
2. There was a server issue on the CoreNLP side and the software/models
couldn't be downloaded.

If the issue is 1, then the proposed workaround would work.
If the issue is 2, then there's nothing we can do on our side, since we
need those files in the processing pipeline.

If you don't want/need to build the image yourself, we provide the prebuilt
docker image (uwcosmos/cosmos:standalone in dockerhub), which includes all
the external dependencies to eliminate this kind of hiccup.
